# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example of cblas_dgemv
#'
#' A function to demo how to use `cblas_dgemv` which perform `z = alpha * X * y + beta * z` with `beta = 0`.
#' This example is based on `https://github.com/Reference-LAPACK/lapack/blob/master/CBLAS/examples/cblas_example1.c`.
#'
#' @param X A matrix.
#' @param y A vector.
#' @param z A vector.
#' @param alpha Numerics.
#' @return A numeric vector. The result of `alpha * X * y`.
#' @examples
#' X <- matrix(1:6, 3, 2)
#' y <- 1:2
#' all.equal(cblas_dgemv_example(X, y), X %*% y) # TRUE
#' @export
cblas_dgemv_example <- function(X, y, alpha = 1) {
    .Call('_RCBLAS_cblas_dgemv_example', PACKAGE = 'RCBLAS', X, y, alpha)
}

